### ISSUE TITLE
IPM S2D check convergence SWAN

### ISSUE THREAD

**Issue by engt2** [witteveenbos/KPZSS#4]
@casvbem: please add example of convergence code

**Comment by casvbem** [comment]
ok here you go!

`
# 1. Import modules 
import numpy as np 
import re

# 2. Define new functions 
def check_swan_convergence(file):
    """
    checks te convergens of the file provided

    Parameters
    ----------
    file : string
        full file path to file to read while checking convergence. This should
        be a prt file

    Returns
    -------
    iteration_list : list 
        with number of iterations
    
    np.transpose(convergence_list) : numpy array
        with convergence percentages
    """
    # Read in the file
    with open(file, 'r') as file :
      filedata = file.read()
    
    #Find all entries between < and > brackets
    match = re.findall(r'accuracy OK in +[\d\d.\d\d]+', filedata)
    
    # Extract all data from the match list that we need and append to returned iteration lists
    iteration_list = []
    convergence_list = []
    
    #Loop over match, which is a list with matched values above
    for p in range(len(match)):
        #Obtain the desired part of the string within the pth value of list
        value = float(match[p].split()[3])
        
        #Append iteration list, p+2 due to counting of python from 0 and first iteration cannot be computed.
        iteration_list.append(p+2)
        
        #Append to convergence list
        convergence_list.append(value)
    return iteration_list, np.transpose(convergence_list)
`
